"""BistableBasins — state separation between the two settled gene levels,
agent (cooperative Hill n=2) vs deterministic policy (expression knob).

The bistable study's finding is structural: a decisive toggle needs COOPERATIVE
mutual repression (Hill n>=2), which destabilises the symmetric state and opens
two basins. The agent recognised this and reached a state separation of 3.46
between the two settled states; the policy only tuned expression strength and
stayed monostable at separation 0. This figure makes that contrast undeniable —
any bar above 0 is a genuinely bistable switch; a bar at 0 is a graded midpoint.

Generated by /viva-viz from request 'bistable-basins'. Demo data are the study's
real reported values (separation 3.46 vs 0).
"""
from __future__ import annotations
import json
from process_bigraph.visualization import as_visualization


@as_visualization(
    inputs={'labels': 'list[string]', 'separation': 'list[float]'},
    name='BistableBasins',
    demo={'labels': ['Agent — cooperative Hill n=2', 'Policy — expression knob'],
          'separation': [3.46, 0.0]},
)
def update_bistable_basins(state):
    """Bar of settled-state separation per build strategy, with the bistability
    threshold marked (separation > 0 => two stable basins)."""
    labels = state['labels']
    sep = state['separation']
    colors = ['#10b981' if v > 0 else '#94a3b8' for v in sep]
    traces = [{
        'x': labels, 'y': sep, 'type': 'bar',
        'marker': {'color': colors},
        'text': [f'{v:.2f}' for v in sep], 'textposition': 'outside',
        'hovertemplate': '%{x}<br>state separation = %{y:.2f}<extra></extra>',
        'name': 'state separation',
    }]
    ymax = max(sep + [1.0]) * 1.25
    layout = {
        'title': {'text': 'Bistability is structural: only cooperative feedback opens two basins'},
        'shapes': [{
            'type': 'line', 'xref': 'paper', 'yref': 'y',
            'x0': 0, 'x1': 1, 'y0': 0.0, 'y1': 0.0,
            'line': {'dash': 'dash', 'color': '#f43f5e', 'width': 1},
        }],
        'annotations': [{
            'xref': 'paper', 'yref': 'paper', 'x': 0.5, 'y': 1.0,
            'text': 'bar > 0 = two distinct stable states (bistable) · bar = 0 = monostable midpoint',
            'showarrow': False, 'font': {'size': 11, 'color': '#475569'},
            'xanchor': 'center', 'yanchor': 'bottom',
        }],
        'margin': {'l': 55, 'r': 20, 't': 60, 'b': 50},
        'xaxis': {'title': {'text': 'model-build strategy'}},
        'yaxis': {'title': {'text': 'state separation |A − B| (a.u.)'}, 'range': [0, ymax]},
    }
    return {'html': (
        '<div id="viz" style="height:380px"></div>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",'
        + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>'
    )}
